export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as Partners } from './Partners'
export { default as HowItWorks } from './HowItWorks'
export { default as CTA } from './CTA'
export { default as WhyChooseUs } from './WhyChooseUs'
